### ISSUE TITLE
How to import data in the app? What format is possible?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-companion-android#3]

**Comment by ty221** [comment]
Without any doubts we can import plain text files, CSV files nad PDF files.
Od course we can import also images and videos. Other formats also may be
importable, but not in so easy way.
W dniu pon., 9 lut 2015 o 23:18 Mario Behling <notifications@github.com>
napisał(a):

**Comment by mariobehling** [comment]
@ty221 
1) Could you describe how the workflow happens? 
2) What structure does a CSV file need to have? Do you have a sample?
3) Where can we store it to update the app?
4) What about the picture file of the map?
5) What would be the way to add photos of speakers in the speakers section?

**Comment by prashantpandeyfun10** [comment]
@mariobehling  what you want to import is the first question one should ask!

**Comment by mariobehling** [comment]
What do we want to import: All information relevant to holding an event: The most obvious ones are times/content of talks, speakers, speaker photos, speaker information and how to get to a location (a map)

**Comment by batraabhishek** [comment]
Currently the app is importing data by calling this API endpoint https://fosdem.org/2015/schedule/xml. Obviously Fossasia need to have its own endpoint for downloading data. The endpoint can return the data in Xml or Json format. From there we can deserialise the data and store it in Sqlite database. The endpoint should also return images url that can be letter used to fetch the images. We can use Volley library for handling network call. It has excellent implementation for network image caching and error handling. But one question here is. Are we targeting an Offline app ? Because in that case we will have to store the images locally.

**Comment by mariobehling** [comment]
Yes, it is important that the app stores data, images, the map locally as people move around and do not have net all the time. A nice workflow from an organizers perspective would be to create a spreadsheet in Google docs with session times, speakers, title, session description, link to picture etc. From the spreadsheet we could then generate an XML or JSON (e.g. using Gadgets). How could such a spreadsheet and "flow" look like? Or, are there better, nicer, alternative ways?

**Comment by sandeepwww** [comment]
I agree with @batraabhishek. The data can be accessed from a CSV( stored in a spreadsheet) or JSON responses . The data and images combined can added from there to a SQLite database.  This can be used inside the app offline. We can provide a refresh like in the fosdem app. On clicking this database will be updated. So user will be to access the data offline. Regarding the maps, fosdem used an image and provided an option to use Google maps, here we can add a feature to save the map locally.
Ps :Looking forward to contribute.

**Comment by batraabhishek** [comment]
@mariobehling I was going through the FOSSASIA site. There is a lot of data available on the site, FOSDEM data is much limited in comparison. I want to ask is the static or is it using custom made API to fetch the data? I have only seen index.html in fossaisa15 repository and everything is static there. So assuming everything is static, we should include the following information in the app:  

**Schedule** - Date, Time, Title, Information, Venue
**Tracks** - Title, Information
**Key Speaker** - Name, Designation, Info, LinkedIn link, Twitter Link, Profile Url
**Speaker** - Name, Designation, Twitter link, LinkedIn link, Profile Url

Why forget the sponsors and organizers :P 
**Sponsors** - Image Url, Web Url
**Organizers**- Name, Designation, Profile Url, Twitter link, LinkedIn link

Here I think a JSON would be great to load the information. All the things in **BOLD** are the categories of information that the app should display. 

Here is the approach i suggest for content updation. Initially app will be shipped with a .json file. When the app is launched, it will make a network call to an api (Basically a url), which will return a version for the data. If the version returned by the api is higher, we will make another call to update the .json file. 

To keep the .apk size low, we can ship the app with some stock images (similar to default user image used by Facebook). And downloading and saving the images asynchronously when the app is running.

PS: We can also use SQLite as suggested by @sandeepwww but since there is no data entry or data manipulation from user end, .json is also an option here.

That is a lot to implement, we can prioritise things and finish things that are of high priority. 

Let me know if this seems good, I will post a sample JSON file soon.

**Comment by mariobehling** [comment]
Hi, this sounds all great. If you are interested in this, just start to adapt the app. From a user perspective of organizers, I suggest: We upload a spreadsheet to Google docs and use a gadget to create the JSON, that can be imported.

**Comment by mananwason** [comment]
I would also like to work on it but I am not too clear on how to get json data from the website ?

**Comment by batraabhishek** [comment]
Okay here it goes :P Basically Google provides API (free) for direct conversion of spreadsheet document to JSON. For example if the spreadsheet URL is https://docs.google.com/spreadsheets/d/1v5-lJlRpWaYNSaxhcGh7jA5k-6WEq4lSHMVxBsvL-C4/ . We need to fetch the key part ie., **lJlRpWaYNSaxhcGh7jA5k-6WEq4lSHMVxBsvL-C4** and append in this URL https://docs.google.com/spreadsheets/d/1v5-lJlRpWaYNSaxhcGh7jA5k-6WEq4lSHMVxBsvL-C4/gviz/tq?pli=1 . @mariobehling So basically organizers need to maintain spreadsheets in a predefined structure (Columns), with public read access and app will directly fetch the JSON data from the URLs (No need of even converting it to JSON).  Let me if that sounds good I will write a module to convert JSON response to SQLite database.

**Comment by mariobehling** [comment]
@batraabhishek Yes, this sounds like a great idea. How would the spreadsheet have to look like? Let's make an example here: https://docs.google.com/spreadsheets/d/13O8ysuMtDGU69JnyZ6yDbzajGQJuDeoLv1zZW94ELXk/edit?usp=sharing

**Comment by batraabhishek** [comment]
@mariobehling We will have to maintain different spreadsheets for different Categories. Like Schedule, Speaker, Sponsors etc. I have added some data for Key Speakers. Here is the JSON link https://docs.google.com/spreadsheets/d/13O8ysuMtDGU69JnyZ6yDbzajGQJuDeoLv1zZW94ELXk/gviz/tq?pli=1

**Comment by mariobehling** [comment]
Would it be possible to do this on different sheets in one document? Also: Speakers and their talks are linked in the app. Does this have any implications?

**Comment by batraabhishek** [comment]
@mariobehling Yes, we can use different sheets in one document. Every sheet has unique GID value associated with it. We can append this GID in the JSON url, to get JSON of the specific sheet. Have a look at the screenshot 

![screen shot 2015-02-16 at 10 44 18 pm](https://cloud.githubusercontent.com/assets/3257840/6216187/862db400-b62d-11e4-9c2c-c22817e90f7d.png)


JSON URL for second sheet

https://docs.google.com/spreadsheets/d/13O8ysuMtDGU69JnyZ6yDbzajGQJuDeoLv1zZW94ELXk/gviz/tq?gid=1746139605

**Comment by batraabhishek** [comment]
**--Speakers and their talks are linked in the app**
@mariobehling We need to find some way to handle joining of different sheets like we do in tables. I will update here once I find something on this

**Comment by batraabhishek** [comment]
@mariobehling I have defined three sheets in the Google Doc link you provided.

1) Speaker
2) Talks
3) Speaker Talks Relation

**Speaker** : List of speakers
**Talks**: List all the information and details related to talks
**Speaker Talks Relation** : Allows only to choose Speaker name and Talk Title from a lost of drop down. The dropdown is generated from the first two sheets. Hence its a kind of joining with foreign key relationship concept. Thus now we have a relation between **Talk <--> Speaker**

**Comment by mariobehling** [comment]
Looks great. How can we get this data now into the app? Could you implement this gateway?

**Comment by batraabhishek** [comment]
Sure, i will start with the module implementation.

**Comment by batraabhishek** [comment]
@mariobehling Please see my updated pull request. I have implemented the module for fetching KeySpeakers and populating them.

PS: I have added Lorem Ipsum data to the above Google Spreadsheet.

**Comment by mariobehling** [comment]
Great! Good job.

**Comment by batraabhishek** [comment]
I have some doubt here. In Fossaisa website, speakers are not linked to their talks. So before implementing it in the app, we need to decide if we wish to link Speakers with talk (as the model for speakers will differ in both case), will the organizers will be able to provide this information ? Till then, I am starting with implementing Schedule and will update here once I am done.

**Comment by sandeepwww** [comment]
@batraabhishek great going.  Could you please let me know if I could help in you in some part of the process? I'd be happy to!

**Comment by batraabhishek** [comment]
@sandeepwww  Yes! Definitely. Please go through the above comments and understand how the data is fetched. If you have any doubt please feel free to ask here. Currently I am working on Key Speaker, and Schedule and events. So we are left with Organizers, Speakers, Sponsors. For starting if you are looking at something easy, you can take up implementing Sponsors. Please go through the app flow. If you have any doubt leave a comment here. 
1) Create a new sheet in the above google doc for the category you are implementing. For example -  If you are starting Sponsors, create a new and make a desired table there. 
2) For fetching go through the JsonToDatabase class. You will get to know how the data is downloaded for KeySpeakers and Schedule. 

PS: please add a comment here about what you are working on so that no two person implement the same thing :P

**Comment by sandeepwww** [comment]
@batraabhishek Should I add a new item to drawer list for sponsors and it's corresponding fragment?

**Comment by batraabhishek** [comment]
@sandeepwww Yes

**Comment by sandeepwww** [comment]
@batraabhishek Perfect. As of now. I'll be working on the Sponsors Fragment
then!

**Comment by batraabhishek** [comment]
@mariobehling Lets try to finish Speakers, Key Speakers, Schedule, Events and Sponsors including bookmark and calendar support by 1st March '15. With this Organizers will get enough time to provide us with data. I am almost done Events. After this I planning to move on to Code cleaning (deleting all the old code that is not used now) and testing. @mariobehling  As Fossasia '15 is approaching should we decide a date for release 1 for the app ?

**Comment by mariobehling** [comment]
Excellent idea. One question I have here - what about talks, that have the same speaker? How should we do that in the spreadsheet?

**Comment by batraabhishek** [comment]
Okay, I have created a separate sheet in the doc. That sheet consist of only two columns, speaker and talks. Speaker columns allows entries from Speaker sheet, And talk column involves events title from events sheet. Now Lets examine all possible combination  in the sheet. A speaker can have multiple talks. And a talk can be given by multiple speakers. I think both the situation is true. But not sure if we should keep the second case or not.  Now when the speaker is clicked we can show all the talks the given by him. And when a talk/event is clicked we will show all the contributing speakers. 

Here is screenshot to make things clear

![screen shot 2015-02-26 at 11 12 36 pm 1](https://cloud.githubusercontent.com/assets/3257840/6397753/13a30d26-be0d-11e4-9947-d7d587320ac5.png)

**Comment by batraabhishek** [comment]
Hi @mariobehling , I need some help here... I am not able to find any speaker data in the Google doc is shared. Can you please point me if I am missing it.

**Comment by batraabhishek** [comment]
Got it.... Its a combination of given name and family name :palm_tree:

**Comment by batraabhishek** [comment]
> My biggest q. is will we be able to import the data from the current spreadsheet format we used this year, but this should be discussed in the other thread, I guess.

I am a bit scared right now to answer this question. I am working on this presently to convert the given data to our docs structure. Just in case, Do we any other option ? In the current doc, we are missing some data, like complete speaker information (including profile pic url etc). So should we remove those things from app?

**Comment by mariobehling** [comment]
The information is not missing. The cells might be hidden. Click the arrows to expand.
![screenshot from 2015-03-05 23 30 12](https://cloud.githubusercontent.com/assets/1583873/6507797/9770ce4a-c38f-11e4-975e-c38ec2618e90.png)

**Comment by batraabhishek** [comment]
@mariobehling  Okay thanks... Can you help me with one more thing.... How is the data fetched in the website.... May b we can use that model easily :) Thanks for your time

**Comment by mariobehling** [comment]
There is no data on the website. We will probably just put a pdf on the site. On Google docs we collected the info through Google forms.

**Comment by batraabhishek** [comment]
Is there any possibility that this data will be updated or is it final?

**Comment by mariobehling** [comment]
95% final. Maybe we could import the data in the app and change the rest by hand if needed. Please let me know, when you import. I would put up the latest versions in the Google doc then.

**Comment by batraabhishek** [comment]
Last thing... Currently there is one sheet for each Talk. Is it possible to export one spreadsheet containing all the data rather then having different sheets for each talk. I don't know what all export options are available while exporting data from google forms. Thanks

**Comment by batraabhishek** [comment]
@mariobehling I am starting to port the current structure, lets make it final. And any changes will be automatically updated on the app (no need to manually update it). I will post an update in few hours

**Comment by mariobehling** [comment]
One sheet is one track and the track is in one room. I added the location information to the bottom of the "Friday Main" Sheet first. Does this work for you like that?

**Comment by batraabhishek** [comment]
Yes, thanks

**Comment by batraabhishek** [comment]
Is it fine If I add one more column **date** in every sheet ?

**Comment by batraabhishek** [comment]
Imported all data except Exhibition... Wheww!! There is no time for exhibition events. Let me know how to proceed with it. @mariobehling @ty221 Please see MR

**Comment by mariobehling** [comment]
ok, sounds great. Can I just copy updated sheets to the spreadsheet on Google or did you change anything, that you need to keep here?

**Comment by batraabhishek** [comment]
You can copy updated data... Just make sure there is a date column present, and it should be the first column in every sheet. There can be some bugs. I will fix it ASAP as they are discovered.

**Comment by mariobehling** [comment]
Ok, copied it. We had to rename some headings in the first row. Please check, if that conflicts when you import. Thanks
