### ISSUE TITLE
Things that need to be fixed urgently.

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/fossasia-companion-android#56]
@mariobehling Kindly list any urgent changes you want with the app. I know Fossasia'15 is already in full swing (Facebook :P), so we cannot do much changes as we don't have much time. But still if you want any things to fixed, please list it here. We will try our best to fix them :D @ty221 Lets launch first release built 1.0 on play store.

**Comment by mariobehling** [comment]
1) If you could implement to show the "moderator"on the talk page (not the talk overview), would be great.
2) If the app could jump to the first day that there is a schedule, e.g. Workshops should jump to March 14 instead of March 13 as the first slide.
2) If there was a link somewhere for people to submit an issue on github, would be good too.
I think other things can be done step by step. What are your ideas?

**Comment by batraabhishek** [comment]
Sounds great :) Will fix these issues first

**Comment by batraabhishek** [comment]
Following two things are fixed: 
>1) If you could implement to show the "moderator"on the talk page (not the talk overview), would be great.
2) If the app could jump to the first day that there is a schedule, e.g. Workshops should jump to March 14 instead of March 13 as the first slide.

@ty221 Can you please release the app on GitHub and Play Store signed with your key. Thanks :)

**Comment by ty221** [comment]
@batraabhishek Hi, of course, I will make release soon, however I will try to fix issue 4) ;)

**Comment by ty221** [comment]
@batraabhishek @mariobehling Fixed 4). Releasing new version :D
