### ISSUE TITLE
Map page not working

### ISSUE THREAD

**Issue by kaine119** [fossasia/fossasia-companion-android#76]
Going to the map page displays an empty map.

A console reveals that an API key for the google maps api is missing.

![console output of app](https://cloud.githubusercontent.com/assets/9492636/12087027/5d7c1e90-b30a-11e5-9c8b-43e82421fd55.png)

**Comment by dalmia** [comment]
This is because the API key is not set in the manifest! If you look at the logcat closely, you can see that beside the API Key its written "API Key here" and if you navigate to AndroidManifest.xml, you can see that for the Google Maps meta data at the end, the value is set to a string resource which in strings.xml is - API key here.
 So to get the maps running :
1. Register the project on Google Developers Console
2. "Enable Google Maps for Android" API 
3. Navigate to the credentials Tab, create a new Android API key and copy the value that you receive in the android:value section of the meta-data tag.
This should fix it.

**Comment by kaine119** [comment]
Alright, thanks
